### ISSUE TITLE
Parse array of numbers and find maximum

### ISSUE THREAD

**Issue by dbvz** [YaroslavUsheta/Javascript-playground#5]
Take a bunch space separated numbers in the input, find maximum, and print.

**Comment by dbvz** [comment]
This is done.

**Comment by dbvz** [comment]
No, this is not yet done. @YaroslavUsheta, do you need any help to finish this?

**Comment by YaroslavUsheta** [comment]
Yes @dbevzenko, can we go over parseInt and parseFloat again?

**Comment by dbvz** [comment]
This is done.
